.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NAMESPACE_EDITOR" "1" "January 2014" "" ""
.
.SH "NAME"
\fBnamespace_editor\fR \- edit namespaces within src files
.
.SH "SYNOPSIS"
\'namespace_editor\' \'\-n\' | \'\-\-new_namespace new_namespace\' \'\-x\' | \'\-\-existing_namespace existing_namespace\' \'\-s\' | \'\-\-src_path src_path\' \'\-e\' | \'\-\-extensions file_extensions\' [\'\-v\' | \'\-\-list output_as_list\']
.
.SH "DESCRIPTION"
\fBnamespace_editor\fR is a command\-line Ruby app to edit/replace namespaces found within src files\. Useful for Android whitelabel apps\. The new namespace replaces the existing namespace in each source file found in the given source path whose extension is one of those in the given list of extensions\.
.
.SH "OPTIONS"
.
.TP
\'\-n\', \'\-\-new_namespace\'
The new namespace
.
.TP
\'\-x\', \'\-\-existing_namespace\'
The namespace to be replaced
.
.TP
\'\-s\', \'\-\-src_path\'
The path to the directory containing the source files to be processed\. Files in sub\-folders will also be processed
.
.TP
\'\-e\', \'\-\-extensions\'
The list of extensions the source files to be processed have\. For multiple extensions this must be a comma separated list
.
.TP
\'\-\-list\'
Switches on list\-style output
.
.TP
\'\-\-overwrite\'
Makes changes to the files \- default is to only report the number of discovered src files
.
.TP
\'\-v\', \'\-\-version\'
Prints the version number\. All other options will be ignored
.
.SH "EXAMPLES"
Replace the namespace \fBcom\.example\.something\fR with the namespace \fBcom\.example\.anotherexample\fR in java and cpp files located at C:\eprojects\emy_project:
.
.P
\fBC:\e>namespace_editor \-n com\.example\.anotherexample \-x com\.example\.something \-s C:\eprojects\emy_project \-e java,cpp \-\-overwrite\fR
.
.SH "LICENCE"
BSD 2\-Clause
.
.SH "AUTHOR"
Barry Drinkwater
.
.br
email: \fIbarry@penrillian\.com\fR
.
.br
web: www\.penrillian\.com \fIhttp://www\.penrillian\.com\fR
.
.br
.
.SH "SEE ALSO"
web: \fIhttps://github\.com/Penrillian/NamespaceEditor\fR
